# SonarQube Configuration for Vanilla HTML/CSS/JS Project

# Project identification - Use your existing project key from SonarCloud
sonar.projectKey=bita
sonar.projectName=DevSecOps
sonar.projectVersion=1.0

# Source code location
sonar.sources=.
sonar.sourceEncoding=UTF-8

# Files to exclude from analysis
sonar.exclusions=**/node_modules/**,**/vendor/**,**/*.min.js,**/*.min.css,**/dist/**,**/build/**,**/.git/**,**/.github/**,**/coverage/**

# Files to include specifically for JavaScript analysis
sonar.inclusions=**/*.js,**/*.html,**/*.css

# Language-specific settings
sonar.javascript.file.suffixes=.js,.jsx
sonar.html.file.suffixes=.html,.htm
sonar.css.file.suffixes=.css,.scss,.sass,.less

# Test coverage (if you have tests)
# sonar.javascript.lcov.reportPaths=coverage/lcov.info
# sonar.testExecutionReportPaths=coverage/test-report.xml

# Quality gate settings
sonar.qualitygate.wait=true

# Additional analysis parameters
sonar.analysis.mode=publish
sonar.scm.provider=git

# Disable rules that might not be relevant for simple HTML/CSS/JS projects
sonar.issue.ignore.multicriteria=e1,e2
sonar.issue.ignore.multicriteria.e1.ruleKey=Web:ImgWithoutAltCheck
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.html
sonar.issue.ignore.multicriteria.e2.ruleKey=css:S4658
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.css
