name: SonarQube Analysis

on:
  push:
    branches:
      - '*'  # Trigger on push to any branch
  pull_request:
    branches:
      - main
      - master
      - develop

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # Shallow clones should be disabled for better analysis
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
      # Only run if package.json exists
      if: hashFiles('package.json') != ''

    - name: Install dependencies
      run: npm ci
      # Only run if package.json exists
      if: hashFiles('package.json') != ''

    - name: Run tests with coverage
      run: |
        if [ -f "package.json" ] && grep -q '"test"' package.json; then
          npm test -- --coverage --watchAll=false
        else
          echo "No test script found in package.json, skipping tests"
        fi
      continue-on-error: true

    - name: SonarQube Scan
      uses: sonarqube-github-actions/sonarqube-scan-action@v2.3.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: SonarQube Quality Gate check
      id: sonarqube-quality-gate-check
      uses: sonarqube-github-actions/sonarqube-quality-gate-action@v1.3.0
      timeout-minutes: 5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    # Optional: Fail the workflow if Quality Gate fails
    - name: "Quality Gate Status"
      run: |
        echo "Quality Gate Status: ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
        if [[ "${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}" == "FAILED" ]]; then
          echo "Quality gate failed"
          exit 1
        fi
